# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Blog"
  pageRef = "blogs"
  weight = 10

[[main]]
  name = "Topics"
  pageRef = "topics"
  weight = 20

# [[main]]
#   name = "Past Projects"
#   pageRef = "projects"
#   weight = 30

# [[main]]
#   identifier = "github"
#   pre = "github"
#   url = "https://github.com/kennethmanuel"
#   weight = 30

# [[main]]
#   identifier = "twitter"
#   pre = "twitter"
#   url = "https://twitter.com/kenneth_manuel_"
#   weight = 40

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

#  [[footer]]
#    name = "Topics"
#    pageRef = "topics"
#    weight = 10

[[footer]]
  name = "About"
  pageRef = "about"
  # url = "https://external-link"